### PR TITLE
resolve #5: Add negated matcher

### LINKED ISSUE #5: have_not_delivered_to matcher for specs
Hi!
How about to add `have_not_deliverd_to` matcher?
This would allow me to rewrite my code

from
```ruby
it "doesn't send notification to listener" do
   expect { subject }.not_to have_delivered_to(EventDelivery, :notify_listener)
end

it "doesn't send notification to manager" do
   expect { subject }.not_to have_delivered_to(EventDelivery, :notify_manager)
end
```
to
```ruby
it "doesn't send notifications to listener and manager" do
   expect { subject }.to have_not_delivered_to(EventDelivery, :notify_listener)
                     .and have_not_delivered_to(EventDelivery, :notify_manager)
end
```

### PR DESCRIPTION
**Pull request by StanisLove**

### CODE REVIEW

**Comment by palkan** [comment]
Rubocop offenses have been fixed in #8. Let's wait for it

**Comment by palkan** [comment]
@StanisLove #8 has been merged, please, rebase.

And don't forget about the changelog and documentation updates.

**Comment by StanisLove** [comment]
Here it is.

**Comment by palkan** [comment]
Thanks!

**Pull request merged**
